name: Update Main Version

on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'

    - name: Version tag only step
      run: |
        echo "Found valid version format in tag!"
        echo "Full version: ${{ steps.version.outputs.full }}"
        echo "Major version: ${{ steps.version.outputs.major }}"
        echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
      if: steps.version.outputs.is_valid == 'true'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Tag new target
      run: git tag -f ${{ steps.version.outputs.major }} ${{ github.ref_name }}
    - name: Push new tag
      run: git push origin ${{ steps.version.outputs.major }} --force
